# -*- coding: utf-8 -*-
"""chatbot2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18_YcIy7o2mcGHD9_Jklxhds0jOA6Cepm

INstalando a biblioteca externa - github
"""

!pip install git+https://github.com/ShoneGK/ChatterPy

"""**Importando as bibliotecas**"""

from chatterbot import ChatBot

#defini o nome do bot
chatbot = ChatBot('Raiza')

from chatterbot.trainers import ListTrainer

#lib para expressao regular
import re

"""**Preparando as conversas**"""

def treinarmento(arquivo):
  conversation = []
  with open(f'/content/{arquivo}.txt', 'r', encoding='utf-8') as f:
      linhas = [linha.strip() for linha in f if linha.strip()]

  for i in range(0, len(linhas), 2):
      perguntas = [p.strip() for p in linhas[i].split(',')]
      resposta = linhas[i+1]
      for pergunta in perguntas:
          conversation.append(pergunta)
          conversation.append(resposta)

  # Treina o bot
  trainer = ListTrainer(chatbot)
  trainer.train(conversation)

"""**Criando o treino do modelo**"""

treinarmento('cnp')

"""**Conversando com o bot**

**Função para armazenar intenções não compreendidas**
"""

def curadoria(text):
  text = str(text)
  file_path = "/content/curadoria.txt"
  with open(file_path, 'a') as file:
    file.write(text + "\n")

pergunta = ""

# Loop de interação
pergunta = ""
while pergunta != "sair":
    pergunta = input("👤Usuário: ").lower()
    if pergunta != "sair":
        resposta = chatbot.get_response(pergunta)
        if float(resposta.confidence) > 0.3:
            print("Adne:", resposta)
        else:
            print("Adne: Ainda não sei responder esta pergunta, estou aprendendo")
            curadoria(pergunta)
    else:
        print("Adne: Foi um prazer conversar com você, até mais!")