# -*- coding: utf-8 -*-
"""chatbot2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18_YcIy7o2mcGHD9_Jklxhds0jOA6Cepm

INstalando a biblioteca externa - github
"""

!pip install git+https://github.com/ShoneGK/ChatterPy

"""**Importando as bibliotecas**"""

from chatterbot import ChatBot

#defini o nome do bot
chatbot = ChatBot('Raiza')

from chatterbot.trainers import ListTrainer

#lib para expressao regular
import re

"""**Preparando as conversas**"""

f = open('/content/saudacao.txt','r')

conversation = []

for line in f:
  m = re.search('(Q:|A:)?(.+)', line)
  if m:
    conversation.append(m.groups()[1])

print(conversation)

"""**Criando o treino do modelo**"""

from chatterbot import trainers
trainer = ListTrainer(chatbot)
trainer.train(conversation)

"""**Conversando com o bot**

**Função para armazenar intenções não compreendidas**
"""

def curadoria(text):
  text = str(text)
  file_path = "/content/curadoria.txt"
  with open(file_path, 'a') as file:
    file.write(text)

pergunta = ""

while pergunta != "sair":
  pergunta = input("👤Usuário: ")
  pergunta = pergunta.lower()
  if(pergunta != "sair"):
    resposta = chatbot.get_response(pergunta)
    if float(resposta.confidence)> 0.3:
      print("🤖Raíza: ",resposta)
    else:
      print("🤖Raíza: Ainda não sei responder esta pergunta, estou aprendendo")
      curadoria(pergunta)
  else:
    print("🤖Raíza: Foi um prazer conversar com você, até mais!")